
name: Push and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

      - name: Login to GAR
        uses: docker/login-action@v2.1.0
        with:
          registry: europe-west2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_CREDENTIALS }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.1.1
        
      - name: Build and push
        uses: docker/build-push-action@v3.3.0
        with:
          push: true
          tags: europe-west2-docker.pkg.dev/comp3006-sms/comp3006-docker/backend:latest
          provenance: false

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: backend
          image: europe-west2-docker.pkg.dev/comp3006-sms/comp3006-docker/backend:latest
          region: europe-west1
